### ISSUE TITLE
Dataset did not match with paper code.

### ISSUE THREAD

**Issue by QaiserShahzad** [omar-mohamed/GPT2-Chest-X-Ray-Report-Generation#10]
Hi,
I am implementing (Automated radiology report generation using conditioned transformers) code, but there is an error of "/IU-XRay/images/CXR1657_IM-0432-3003.png'" path issue. There are no .png images are available in IU-Xray dataset. Only .csv file are available by this image name.
Please if you have a dataset regarding this paper, share a downloadable link with me. So that I proceed my implementation task.
Thanks .
Qaiser Shahzad
qaisershahzad216@gmail.com
Comsats University Islamabad, Pakistan

**Comment by omar-mohamed** [comment]
Hello Qaisar,
Please run `get_iu_xray.py` to download the dataset.
