### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by aviezab** [omar-mohamed/GPT2-Chest-X-Ray-Report-Generation#4]
Hi @omar-mohamed,
Thanks for making such beautiful code repository and I'd learn from it.

You forgot to include the license, since I want to modify it in the future,
Thanks,
aviezab

**Comment by omar-mohamed** [comment]
Hello @aviezab 
Thank you for bringing this to my attention. I added the license now, please feel free to build upon it as long as you attribute the original work. 
Looking forward to seeing your modifications.
