### ISSUE TITLE
Why is there an optimizer in the test.py file?

### ISSUE THREAD

**Issue by VaticanCameos99** [omar-mohamed/GPT2-Chest-X-Ray-Report-Generation#5]
Hey, I found the following lines in test.py:

`
    optimizer = tf.keras.optimizers.Adam()

    ckpt = tf.train.Checkpoint(encoder=encoder,
                               decoder=decoder,
                               optimizer=optimizer)

    ckpt_manager = tf.train.CheckpointManager(ckpt, FLAGS.ckpt_path, max_to_keep=1)`

And I am also not sure where are the model weights loaded. 
Why are the above lines needed at inference time?

**Comment by omar-mohamed** [comment]
Hello,
I send the optimizer because the TensorFlow version that I started with required an optimizer to be passed.
CheckpointManager takes a ckpt_path and the model weights are loaded in this part:
```
ckpt.restore(ckpt_manager.latest_checkpoint)
```
I hope this helps.

**Comment by VaticanCameos99** [comment]
Hi, thanks for your reply!

I still have a few doubts, I am new to tensorflow.

I downloaded the checkpoint from the drive link and placed it in an appropriate folder, gave the path to that folder in configs.py under ckpt_path. (Used absolute paths)

When I run the code, I get the following error:
`tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /content/drive/MyDrive/new/GPT2-Chest-X-Ray-Report-Generation/ckpt-27`

I used the 'checkpoint_name' function parameter of the CheckpointManager  to redirect it to the right filename, but now my latest_checkpoint is None. What could be the reason?

**Comment by omar-mohamed** [comment]
Hey,

I just tried it on googleColab using TF 2.1 and it worked normally. I just pointed to the folder containing the checkpoint in config.py under ckpt_path using absolute paths like the following:
```
/content/drive/My Drive/colab/GPT2-Chest-X-Ray-Report-Generation/checkpoints/paper-ckpt
```
or a relative path 
```
./checkpoints/paper-ckpt
```

No need to use 'checkpoint_name' as CheckpointManager automatically fetches the latest checkpoint from the folder. If it's still not working try to check if the folder is readable from your directory using 
```
import os

if os.path.exists('path_to_folder_or_file'):
   print("found")
```

**Comment by VaticanCameos99** [comment]
Hey, the issue is resolved. I just picked the 'checkpoint' fild from the drive rather than the whole folder. 

Thanks a lot.
